name: Aipapa
options:
  bundleIdPrefix: com.iphonjb
configs:
  Debug: debug
  Release: release
targets:
  Aipapa:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - Sources
    settings:
      INFO_PLIST_FILE: Info.plist
      PRODUCT_BUNDLE_IDENTIFIER: com.iphonjb.aipapa
